-   hosts: localhost
    become: yes
    become_user: root
    vars:
        app_dir: ./redis
    tasks:
        - name: Run docker
          docker_container:
            name: ddosredis
            image: redis
            state: started
            published_ports:
              - 0.0.0.0:6379:6379
